// <auto-generated />
using System;
using Hospital.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital.Data.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20260402120044_AddCityEntity")]
    partial class AddCityEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital.Data.Entities.Checkup", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("DoctorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("ID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.ToTable("Checkups");

                    b.HasData(
                        new
                        {
                            ID = new Guid("d44665d6-6b30-4542-b932-cbb7ee71efbe"),
                            Date = new DateOnly(2026, 4, 12),
                            DoctorID = new Guid("08ccdf4b-02ad-464f-9ef2-fb73ceee1826"),
                            PatientID = new Guid("9783d8b3-014f-477a-b951-6ff87057b44f"),
                            Time = new TimeOnly(16, 30, 0)
                        },
                        new
                        {
                            ID = new Guid("7f55e59e-5ab2-4e36-92bd-d66f3c453ab9"),
                            Date = new DateOnly(2026, 6, 1),
                            DoctorID = new Guid("3480fb00-bfdc-4139-91a3-a975153ab6b3"),
                            PatientID = new Guid("06999216-e4e9-4455-856d-5246259b2684"),
                            Time = new TimeOnly(16, 30, 0)
                        },
                        new
                        {
                            ID = new Guid("5dad99cf-b93a-4376-b772-86fd44246d7e"),
                            Date = new DateOnly(2026, 7, 19),
                            DoctorID = new Guid("3480fb00-bfdc-4139-91a3-a975153ab6b3"),
                            PatientID = new Guid("eac603b7-4022-4fb1-8c04-28db2f0f2162"),
                            Time = new TimeOnly(8, 30, 0)
                        },
                        new
                        {
                            ID = new Guid("a828ee04-c7dc-417c-9d8b-85114a92ce47"),
                            Date = new DateOnly(2026, 12, 6),
                            DoctorID = new Guid("3480fb00-bfdc-4139-91a3-a975153ab6b3"),
                            PatientID = new Guid("ba24d819-24f4-4e94-bb71-77765076d46c"),
                            Time = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            ID = new Guid("aff1363e-af23-4c5b-a88f-ba81e536333b"),
                            Date = new DateOnly(2026, 5, 23),
                            DoctorID = new Guid("3480fb00-bfdc-4139-91a3-a975153ab6b3"),
                            PatientID = new Guid("718919c3-760f-4a6a-8abf-b1cd1b459d11"),
                            Time = new TimeOnly(15, 30, 0)
                        });
                });

            modelBuilder.Entity("Hospital.Data.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Hospital.Data.Entities.Medication", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DiagnoseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SideEffects")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DiagnoseID");

                    b.ToTable("Medications");

                    b.HasData(
                        new
                        {
                            ID = new Guid("95344cea-8f8e-413e-8f2f-769749bee51b"),
                            Description = "Pain relief",
                            DiagnoseID = new Guid("0b0a943c-4d25-4b22-b21f-ee4f80f8e6b0"),
                            Name = "Paracetamol",
                            SideEffects = "Nausea"
                        },
                        new
                        {
                            ID = new Guid("754771d0-8581-4a0b-aa8e-fe312d90e5a5"),
                            Description = "Anti inflammatory",
                            DiagnoseID = new Guid("02ce1c83-0198-4d90-9dc1-d697c61f936e"),
                            Name = "Ibuprofen",
                            SideEffects = "Stomach pain"
                        },
                        new
                        {
                            ID = new Guid("7cf144e7-7d29-4991-948d-ffb592c85488"),
                            Description = "Antibiotic",
                            DiagnoseID = new Guid("2edd634a-5c31-4f68-b9b5-58c2f5b80216"),
                            Name = "Amoxicillin",
                            SideEffects = "Allergy"
                        },
                        new
                        {
                            ID = new Guid("3857c780-691f-4ef1-ae47-853911e00a97"),
                            Description = "Blood thinner",
                            DiagnoseID = new Guid("732a09fb-ad41-4059-829b-8f32cbf0ce2f"),
                            Name = "Aspirin",
                            SideEffects = "Bleeding"
                        },
                        new
                        {
                            ID = new Guid("04e1b6ac-4511-4cb2-91ad-ff8d8bf095c5"),
                            Description = "Diabetes medication",
                            DiagnoseID = new Guid("46a961d1-e24f-4029-9c13-4ee9a345610c"),
                            Name = "Metformin",
                            SideEffects = "Fatigue"
                        },
                        new
                        {
                            ID = new Guid("a73e5de4-cbe9-4e87-87a7-39230af38a1e"),
                            Description = "Blood pressure",
                            DiagnoseID = new Guid("732a09fb-ad41-4059-829b-8f32cbf0ce2f"),
                            Name = "Lisinopril",
                            SideEffects = "Cough"
                        },
                        new
                        {
                            ID = new Guid("ea31422a-7b5b-42f1-a476-b9aaab041732"),
                            Description = "Acid reflux",
                            DiagnoseID = new Guid("c97e4a52-4926-4268-8261-82739340e77b"),
                            Name = "Omeprazole",
                            SideEffects = "Headache"
                        });
                });

            modelBuilder.Entity("Hospital.Data.Entities.Patient", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BirthCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DischargeDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("DischargeTime")
                        .HasColumnType("time");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("HospitalizationDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HospitalizationTime")
                        .HasColumnType("time");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UCN")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("DoctorId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            ID = new Guid("9783d8b3-014f-477a-b951-6ff87057b44f"),
                            BirthCity = "Kazanlak",
                            DateOfBirth = new DateOnly(2007, 10, 16),
                            DischargeDate = new DateOnly(2026, 6, 17),
                            DischargeTime = new TimeOnly(12, 30, 0),
                            DoctorId = new Guid("6d3dacc1-3b7a-4e43-8caa-5b82a6f4a21f"),
                            HospitalizationDate = new DateOnly(2026, 5, 12),
                            HospitalizationTime = new TimeOnly(10, 30, 0),
                            PhoneNumber = "0878104032",
                            RoomId = new Guid("e748053a-f20a-4f80-a314-fbd9c2ac4e8a"),
                            UCN = "0750167656",
                            UserId = new Guid("a7e0d718-a822-48db-b8ff-82cff6dbd5c7")
                        },
                        new
                        {
                            ID = new Guid("eac603b7-4022-4fb1-8c04-28db2f0f2162"),
                            BirthCity = "Stara Zagora",
                            DateOfBirth = new DateOnly(1992, 11, 23),
                            DischargeDate = new DateOnly(2026, 3, 15),
                            DischargeTime = new TimeOnly(11, 0, 0),
                            DoctorId = new Guid("0f6d5fde-bc75-4df5-8886-090806665b82"),
                            HospitalizationDate = new DateOnly(2026, 3, 1),
                            HospitalizationTime = new TimeOnly(14, 45, 0),
                            PhoneNumber = "0882123456",
                            RoomId = new Guid("0de4b3b8-318e-42aa-b896-04cd14749d17"),
                            UCN = "9251237890",
                            UserId = new Guid("04347895-6b6e-4608-be4c-5f428b759669")
                        },
                        new
                        {
                            ID = new Guid("06999216-e4e9-4455-856d-5246259b2684"),
                            BirthCity = "Plovdiv",
                            DateOfBirth = new DateOnly(1994, 3, 15),
                            DischargeDate = new DateOnly(2026, 7, 20),
                            DischargeTime = new TimeOnly(11, 30, 0),
                            DoctorId = new Guid("dcd275c5-67c4-423b-a7b2-78ab917a2d5d"),
                            HospitalizationDate = new DateOnly(2026, 7, 5),
                            HospitalizationTime = new TimeOnly(9, 0, 0),
                            PhoneNumber = "0877123456",
                            RoomId = new Guid("53546e3d-53ee-4e2c-861a-3cf5a3584893"),
                            UCN = "9413153443",
                            UserId = new Guid("96747275-9c90-449e-a91c-eb6863183a27")
                        },
                        new
                        {
                            ID = new Guid("718919c3-760f-4a6a-8abf-b1cd1b459d11"),
                            BirthCity = "Yambol",
                            DateOfBirth = new DateOnly(1995, 8, 12),
                            DischargeDate = new DateOnly(2026, 4, 24),
                            DischargeTime = new TimeOnly(15, 30, 0),
                            DoctorId = new Guid("2a4e1d97-8411-4cf8-9da2-af9452f16eca"),
                            HospitalizationDate = new DateOnly(2026, 4, 18),
                            HospitalizationTime = new TimeOnly(11, 0, 0),
                            PhoneNumber = "0891122334",
                            RoomId = new Guid("85242158-d3c2-4542-bc27-88caf4a131c6"),
                            UCN = "9548127883",
                            UserId = new Guid("865c2545-7806-4857-a621-f035e520a596")
                        },
                        new
                        {
                            ID = new Guid("ba24d819-24f4-4e94-bb71-77765076d46c"),
                            BirthCity = "Sofia",
                            DateOfBirth = new DateOnly(2002, 9, 15),
                            DischargeDate = new DateOnly(2026, 6, 15),
                            DischargeTime = new TimeOnly(12, 30, 0),
                            DoctorId = new Guid("3480fb00-bfdc-4139-91a3-a975153ab6b3"),
                            HospitalizationDate = new DateOnly(2026, 6, 1),
                            HospitalizationTime = new TimeOnly(9, 45, 0),
                            PhoneNumber = "0881239876",
                            RoomId = new Guid("c219c792-8a69-4850-ac40-a36f5f752786"),
                            UCN = "0249152349",
                            UserId = new Guid("c5982307-ef67-4b65-b438-8f9e1e3a240b")
                        });
                });

            modelBuilder.Entity("Hospital.Data.Entities.Shift", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            ID = new Guid("0288c0db-23d0-4cef-b74c-ef997285b18c"),
                            EndTime = new TimeOnly(14, 0, 0),
                            StartTime = new TimeOnly(6, 0, 0),
                            Type = "Morning"
                        },
                        new
                        {
                            ID = new Guid("2cd29802-44c5-4559-8cc3-225984ae748f"),
                            EndTime = new TimeOnly(22, 0, 0),
                            StartTime = new TimeOnly(14, 0, 0),
                            Type = "Afternoon"
                        },
                        new
                        {
                            ID = new Guid("baaafe92-5c0f-420b-87f0-fb1da4868b41"),
                            EndTime = new TimeOnly(6, 0, 0),
                            StartTime = new TimeOnly(22, 0, 0),
                            Type = "Night"
                        },
                        new
                        {
                            ID = new Guid("3ba89da5-3a0d-44ff-97f9-f049bc9bdbe9"),
                            EndTime = new TimeOnly(8, 0, 0),
                            StartTime = new TimeOnly(0, 0, 0),
                            Type = "Emergency"
                        },
                        new
                        {
                            ID = new Guid("aaaaaaf9-5059-478c-8df4-db3fd4342b14"),
                            EndTime = new TimeOnly(16, 0, 0),
                            StartTime = new TimeOnly(8, 0, 0),
                            Type = "Weekend"
                        });
                });

            modelBuilder.Entity("Hospital.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e7d8baba-f7b1-4ed0-9bbb-139dc13e878e"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C1",
                            Email = "kristeng@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "KRISTEN",
                            LastName = "GENCHEVA",
                            LockoutEnabled = false,
                            NormalizedEmail = "KRISTENG@GMAIL.COM",
                            NormalizedUserName = "KRISTEN_GENCHEVA",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S1",
                            TwoFactorEnabled = false,
                            UserName = "kristen_gencheva"
                        },
                        new
                        {
                            Id = new Guid("072eae42-46ab-4919-aae5-073aef56c00d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C2",
                            Email = "ivanp@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Ivan",
                            LastName = "Petrov",
                            LockoutEnabled = false,
                            NormalizedEmail = "IVANP@GMAIL.COM",
                            NormalizedUserName = "IVAN_PETROV",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S2",
                            TwoFactorEnabled = false,
                            UserName = "ivan_petrov"
                        },
                        new
                        {
                            Id = new Guid("7c425879-d37a-48a6-91d9-2345120a3f6a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C3",
                            Email = "gergid@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Georgi",
                            LastName = "Dimitrov",
                            LockoutEnabled = false,
                            NormalizedEmail = "GEORGID@GMAIL.COM",
                            NormalizedUserName = "GEORGI_DIMITROV",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S3",
                            TwoFactorEnabled = false,
                            UserName = "georgi_dimitrov"
                        },
                        new
                        {
                            Id = new Guid("3d86822f-0eba-44ce-8484-27addbfe7357"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C4",
                            Email = "nikolaii@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Nikolai",
                            LastName = "Ivanov",
                            LockoutEnabled = false,
                            NormalizedEmail = "NIKOLAII@GMAIL.COM",
                            NormalizedUserName = "NIKOLAI_IVANOV",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S4",
                            TwoFactorEnabled = false,
                            UserName = "nikolai_ivanov"
                        },
                        new
                        {
                            Id = new Guid("7dca2bf8-df73-4dbf-a602-52e147eafe1e"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C5",
                            Email = "dimiturs@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Dimitur",
                            LastName = "Stoyanov",
                            LockoutEnabled = false,
                            NormalizedEmail = "DIMITURS@GMAIL.COM",
                            NormalizedUserName = "DIMITUR_STOYANOV",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S5",
                            TwoFactorEnabled = false,
                            UserName = "dimitur_stoyanov"
                        },
                        new
                        {
                            Id = new Guid("23b350b4-0dd6-43fc-b5dc-818faf2b74e6"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C6",
                            Email = "aleksandurn@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Aleksandur",
                            LastName = "Nikolov",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALEKSANDURN@GMAIL.COM",
                            NormalizedUserName = "ALEKSANDUR_NIKOLOV",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S6",
                            TwoFactorEnabled = false,
                            UserName = "aleksandur_nikolov"
                        },
                        new
                        {
                            Id = new Guid("d9ccb374-6b17-4e66-9c11-79412a9e1e93"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C7",
                            Email = "yoanai@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Yoana",
                            LastName = "Ilieva",
                            LockoutEnabled = false,
                            NormalizedEmail = "YOANAI@GMAIL.COM",
                            NormalizedUserName = "YOANA_ILIEVA",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S7",
                            TwoFactorEnabled = false,
                            UserName = "yoana_ilieva"
                        },
                        new
                        {
                            Id = new Guid("30f2b4ed-e0e3-4443-8595-4dc6e26b3338"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C8",
                            Email = "viktoriyan@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Viktoriya",
                            LastName = "Nikolova",
                            LockoutEnabled = false,
                            NormalizedEmail = "VIKTORIYAN@GMAIL.COM",
                            NormalizedUserName = "VIKTORIYA_NIKOLOVA",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S8",
                            TwoFactorEnabled = false,
                            UserName = "viktoriya_nikolova"
                        },
                        new
                        {
                            Id = new Guid("51daaed0-67e7-4c4a-b254-2745af5365df"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C9",
                            Email = "annaa@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Anna",
                            LastName = "Aleksandrova",
                            LockoutEnabled = false,
                            NormalizedEmail = "ANNAA@GMAIL.COM",
                            NormalizedUserName = "ANNA_ALEKSANDROVA",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S9",
                            TwoFactorEnabled = false,
                            UserName = "anna_aleksandrova"
                        },
                        new
                        {
                            Id = new Guid("cbdfa704-0f6d-431f-8ede-dd952adacfc9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C10",
                            Email = "elenap@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Elena",
                            LastName = "Petrova",
                            LockoutEnabled = false,
                            NormalizedEmail = "ELENAP@GMAIL.COM",
                            NormalizedUserName = "ELENA_PETROVA",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S10",
                            TwoFactorEnabled = false,
                            UserName = "elena_petrova"
                        },
                        new
                        {
                            Id = new Guid("f6662c6a-414b-4b5c-ae1b-7b31103dd464"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C11",
                            Email = "aleksandrag@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Aleksandra",
                            LastName = "Georgieva",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALEKSANDRAG@GMAIL.COM",
                            NormalizedUserName = "ALEKSANDRA_GEORGIEVA",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S11",
                            TwoFactorEnabled = false,
                            UserName = "aleksandra_georgieva"
                        },
                        new
                        {
                            Id = new Guid("354fa92a-6b54-4d12-b90c-9926dc906462"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C12",
                            Email = "mariai@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Maria",
                            LastName = "Ivanova",
                            LockoutEnabled = false,
                            NormalizedEmail = "MARIAI@GMAIL.COM",
                            NormalizedUserName = "MARIA_IVANOVA",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S12",
                            TwoFactorEnabled = false,
                            UserName = "maria_ivanova"
                        },
                        new
                        {
                            Id = new Guid("02e72b22-0abd-4ce4-80d1-30b8c13f952b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C13",
                            Email = "desid@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Desislava",
                            LastName = "Dimitrova",
                            LockoutEnabled = false,
                            NormalizedEmail = "DESID@GMAIL.COM",
                            NormalizedUserName = "DESISLAVA_DIMITROVA",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S13",
                            TwoFactorEnabled = false,
                            UserName = "desislava_dimitrova"
                        },
                        new
                        {
                            Id = new Guid("741d970d-f405-4bd1-94b2-eec2c3fb33e2"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C14",
                            Email = "gerganav@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Gergana",
                            LastName = "Vasileva",
                            LockoutEnabled = false,
                            NormalizedEmail = "GERGANAV@GMAIL.COM",
                            NormalizedUserName = "GERGANA_VASILEVA",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S14",
                            TwoFactorEnabled = false,
                            UserName = "gergana_vasileva"
                        },
                        new
                        {
                            Id = new Guid("355ad73e-6b7d-4ade-846d-7cab0da06629"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C15",
                            Email = "ralitsak@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Ralitsa",
                            LastName = "Kostova",
                            LockoutEnabled = false,
                            NormalizedEmail = "RALITSAK@GMAIL.COM",
                            NormalizedUserName = "RALITSA_KOSTOVA",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S15",
                            TwoFactorEnabled = false,
                            UserName = "ralitsa_kostova"
                        },
                        new
                        {
                            Id = new Guid("a7e0d718-a822-48db-b8ff-82cff6dbd5c7"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C16",
                            Email = "petarg@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Petar",
                            LastName = "Georgiev",
                            LockoutEnabled = false,
                            NormalizedEmail = "PETARG@GMAIL.COM",
                            NormalizedUserName = "PETAR_GEORGIEV",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S16",
                            TwoFactorEnabled = false,
                            UserName = "petar_georgiev"
                        },
                        new
                        {
                            Id = new Guid("04347895-6b6e-4608-be4c-5f428b759669"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C17",
                            Email = "stefank@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Stefan",
                            LastName = "Kolev",
                            LockoutEnabled = false,
                            NormalizedEmail = "STEFANK@GMAIL.COM",
                            NormalizedUserName = "STEFAN_KOLEV",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S17",
                            TwoFactorEnabled = false,
                            UserName = "stefan_kolev"
                        },
                        new
                        {
                            Id = new Guid("96747275-9c90-449e-a91c-eb6863183a27"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C18",
                            Email = "borislavt@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Borislav",
                            LastName = "Todorov",
                            LockoutEnabled = false,
                            NormalizedEmail = "BORISLAVT@GMAIL.COM",
                            NormalizedUserName = "BORISLAV_TODOROV",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S18",
                            TwoFactorEnabled = false,
                            UserName = "borislav_todorov"
                        },
                        new
                        {
                            Id = new Guid("865c2545-7806-4857-a621-f035e520a596"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C19",
                            Email = "hristov@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Hristo",
                            LastName = "Vasilev",
                            LockoutEnabled = false,
                            NormalizedEmail = "HRISTOV@GMAIL.COM",
                            NormalizedUserName = "HRISTO_VASILEV",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S19",
                            TwoFactorEnabled = false,
                            UserName = "hristo_vasilev"
                        },
                        new
                        {
                            Id = new Guid("c5982307-ef67-4b65-b438-8f9e1e3a240b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C20",
                            Email = "martini@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Martin",
                            LastName = "Iliev",
                            LockoutEnabled = false,
                            NormalizedEmail = "MARTINI@GMAIL.COM",
                            NormalizedUserName = "MARTIN_ILIEV",
                            PasswordHash = "HASH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "S20",
                            TwoFactorEnabled = false,
                            UserName = "martin_iliev"
                        });
                });

            modelBuilder.Entity("Hospital.Entities.Diagnose", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PublicID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Diagnoses");

                    b.HasData(
                        new
                        {
                            ID = new Guid("91b25ace-9e01-4c25-b0ea-3c8bad060315"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775043137/716959ed-ecf1-4c3e-a6ad-dfb7caca7863_mxmyot.png",
                            Name = "Influenza",
                            PublicID = "716959ed-ecf1-4c3e-a6ad-dfb7caca7863"
                        },
                        new
                        {
                            ID = new Guid("732a09fb-ad41-4059-829b-8f32cbf0ce2f"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/v1774523282/5ab0f5a2-2ef5-4769-b2a7-9e485afd8a21.png",
                            Name = "Hypertension",
                            PublicID = "5ab0f5a2-2ef5-4769-b2a7-9e485afd8a21"
                        },
                        new
                        {
                            ID = new Guid("46a961d1-e24f-4029-9c13-4ee9a345610c"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/v1774522900/79aadf40-1666-44d1-8a39-b72d08f433ac.png",
                            Name = "Diabetes",
                            PublicID = "79aadf40-1666-44d1-8a39-b72d08f433ac"
                        },
                        new
                        {
                            ID = new Guid("2edd634a-5c31-4f68-b9b5-58c2f5b80216"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/v1774522988/12f38fbe-0962-464f-89fc-26cf3598a478.png",
                            Name = "Pneumonia",
                            PublicID = "12f38fbe-0962-464f-89fc-26cf3598a478"
                        },
                        new
                        {
                            ID = new Guid("0b0a943c-4d25-4b22-b21f-ee4f80f8e6b0"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/v1774523421/31435cc9-7c7f-47ba-94c6-8e14a8790876.png",
                            Name = "Migraine",
                            PublicID = "31435cc9-7c7f-47ba-94c6-8e14a8790876"
                        },
                        new
                        {
                            ID = new Guid("02ce1c83-0198-4d90-9dc1-d697c61f936e"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/v1774523396/de9b8762-40d7-459f-9f11-aeb90f41f4a8.png",
                            Name = "Fracture",
                            PublicID = "de9b8762-40d7-459f-9f11-aeb90f41f4a8"
                        },
                        new
                        {
                            ID = new Guid("d793f73f-51a0-4ff0-b6fa-5ffd4d47cd15"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/v1774523070/38a63bdf-b3a2-4719-91d1-e874170d0387.png",
                            Name = "Asthma",
                            PublicID = "38a63bdf-b3a2-4719-91d1-e874170d0387"
                        },
                        new
                        {
                            ID = new Guid("c97e4a52-4926-4268-8261-82739340e77b"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/v1774523162/1c6fae53-754a-48e0-92ba-309ceaed5972.png",
                            Name = "Raynauld's syndrome",
                            PublicID = "1c6fae53-754a-48e0-92ba-309ceaed5972"
                        },
                        new
                        {
                            ID = new Guid("885aea72-26c5-48b5-88cc-7128b7e81499"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/v1774523117/88005d89-b665-4fac-b2a8-1325f75a2809.png",
                            Name = "Osteoporosis",
                            PublicID = "88005d89-b665-4fac-b2a8-1325f75a2809"
                        },
                        new
                        {
                            ID = new Guid("49a578fc-5f30-40b6-810f-3ca54b0e2a02"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/v1774522872/f83a45f2-58db-4045-99a9-8b5829b13f05.png",
                            Name = "Hashimoto's disease",
                            PublicID = "f83a45f2-58db-4045-99a9-8b5829b13f05"
                        },
                        new
                        {
                            ID = new Guid("2dfdf306-41d8-4aca-abd6-91ed7d4adc8a"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775043330/c4510bbe-5309-4952-9ccd-326308a2c64a_vy0qwz.png",
                            Name = "Bronchitis",
                            PublicID = "c4510bbe-5309-4952-9ccd-326308a2c64a_vy0qwz"
                        });
                });

            modelBuilder.Entity("Hospital.Entities.Doctor", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CloudinaryID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ShiftId");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            ID = new Guid("08ccdf4b-02ad-464f-9ef2-fb73ceee1826"),
                            CloudinaryID = "doctor6_tvjvud",
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775045919/doctor6_tvjvud.jpg",
                            IsAccepted = true,
                            ShiftId = new Guid("3ba89da5-3a0d-44ff-97f9-f049bc9bdbe9"),
                            SpecializationId = new Guid("8a42cdba-ff58-4129-aea8-ae4c3b32f353"),
                            UserId = new Guid("072eae42-46ab-4919-aae5-073aef56c00d")
                        },
                        new
                        {
                            ID = new Guid("e1ceefa2-e56b-4395-9049-c689bea9417f"),
                            CloudinaryID = "doctor5_vwg329",
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775045919/doctor5_vwg329.jpg",
                            IsAccepted = true,
                            ShiftId = new Guid("0288c0db-23d0-4cef-b74c-ef997285b18c"),
                            SpecializationId = new Guid("7a67c94b-50fb-4043-83f1-afdade20b451"),
                            UserId = new Guid("7c425879-d37a-48a6-91d9-2345120a3f6a")
                        },
                        new
                        {
                            ID = new Guid("186296e2-7114-4291-aa3b-897b96c75c21"),
                            CloudinaryID = "doctor4_cnmqpg",
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775045919/doctor4_cnmqpg.jpg",
                            IsAccepted = true,
                            ShiftId = new Guid("baaafe92-5c0f-420b-87f0-fb1da4868b41"),
                            SpecializationId = new Guid("c484edec-d525-438a-92c4-ad80a9a41878"),
                            UserId = new Guid("3d86822f-0eba-44ce-8484-27addbfe7357")
                        },
                        new
                        {
                            ID = new Guid("2a4e1d97-8411-4cf8-9da2-af9452f16eca"),
                            CloudinaryID = "doctor3_djf78l",
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775045922/doctor3_djf78l.jpg",
                            IsAccepted = true,
                            ShiftId = new Guid("aaaaaaf9-5059-478c-8df4-db3fd4342b14"),
                            SpecializationId = new Guid("9cfb1a19-193f-4bf7-bc4b-c744a89f59eb"),
                            UserId = new Guid("7dca2bf8-df73-4dbf-a602-52e147eafe1e")
                        },
                        new
                        {
                            ID = new Guid("3480fb00-bfdc-4139-91a3-a975153ab6b3"),
                            CloudinaryID = "doctor2_x95tr9",
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775045917/doctor2_x95tr9.jpg",
                            IsAccepted = true,
                            ShiftId = new Guid("0288c0db-23d0-4cef-b74c-ef997285b18c"),
                            SpecializationId = new Guid("1d3e1ea9-5265-4ff3-9875-d7ac37a2d8b2"),
                            UserId = new Guid("23b350b4-0dd6-43fc-b5dc-818faf2b74e6")
                        },
                        new
                        {
                            ID = new Guid("8e296807-75cf-45dd-bdfc-179495465c09"),
                            CloudinaryID = "doctor1_jiqipy",
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775045917/doctor1_jiqipy.jpg",
                            IsAccepted = true,
                            ShiftId = new Guid("baaafe92-5c0f-420b-87f0-fb1da4868b41"),
                            SpecializationId = new Guid("e43cf086-24ad-4a75-b47e-549b8d8e467c"),
                            UserId = new Guid("d9ccb374-6b17-4e66-9c11-79412a9e1e93")
                        },
                        new
                        {
                            ID = new Guid("26189d95-7ca7-40f7-9384-8454cfb99247"),
                            CloudinaryID = "doctor9_ksvypt",
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775045917/doctor9_ksvypt.jpg",
                            IsAccepted = true,
                            ShiftId = new Guid("aaaaaaf9-5059-478c-8df4-db3fd4342b14"),
                            SpecializationId = new Guid("e82cc806-165f-4554-91f8-c9d9ae4909e5"),
                            UserId = new Guid("30f2b4ed-e0e3-4443-8595-4dc6e26b3338")
                        },
                        new
                        {
                            ID = new Guid("6d3dacc1-3b7a-4e43-8caa-5b82a6f4a21f"),
                            CloudinaryID = "f4c9ef33d04a22050038e9e53eeb7d85_w2l72d",
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775044425/f4c9ef33d04a22050038e9e53eeb7d85_w2l72d.jpg",
                            IsAccepted = true,
                            ShiftId = new Guid("2cd29802-44c5-4559-8cc3-225984ae748f"),
                            SpecializationId = new Guid("c484edec-d525-438a-92c4-ad80a9a41878"),
                            UserId = new Guid("51daaed0-67e7-4c4a-b254-2745af5365df")
                        },
                        new
                        {
                            ID = new Guid("0f6d5fde-bc75-4df5-8886-090806665b82"),
                            CloudinaryID = "doctor8_daewlm",
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775045915/doctor8_daewlm.jpg",
                            IsAccepted = true,
                            ShiftId = new Guid("baaafe92-5c0f-420b-87f0-fb1da4868b41"),
                            SpecializationId = new Guid("4ee4ce69-da26-4f66-85cf-30623200cbf4"),
                            UserId = new Guid("cbdfa704-0f6d-431f-8ede-dd952adacfc9")
                        },
                        new
                        {
                            ID = new Guid("dcd275c5-67c4-423b-a7b2-78ab917a2d5d"),
                            CloudinaryID = "doctor7_ylf8tt",
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775045915/doctor7_ylf8tt.jpg",
                            IsAccepted = true,
                            ShiftId = new Guid("2cd29802-44c5-4559-8cc3-225984ae748f"),
                            SpecializationId = new Guid("a5519f22-cefb-4771-a5e9-de7b40817df8"),
                            UserId = new Guid("f6662c6a-414b-4b5c-ae1b-7b31103dd464")
                        });
                });

            modelBuilder.Entity("Hospital.Entities.DoctorAndNurse", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NurseID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("NurseID");

                    b.HasIndex("DoctorID", "NurseID")
                        .IsUnique();

                    b.ToTable("DoctorsAndNurses");

                    b.HasData(
                        new
                        {
                            ID = new Guid("c5c2c0dd-c326-4f37-804c-e53354c825ed"),
                            DoctorID = new Guid("e1ceefa2-e56b-4395-9049-c689bea9417f"),
                            NurseID = new Guid("698d0579-913c-42af-8a45-924cd9f740bb")
                        },
                        new
                        {
                            ID = new Guid("5a6d7c84-48ec-4b3c-a2d6-a468f92f12dc"),
                            DoctorID = new Guid("8e296807-75cf-45dd-bdfc-179495465c09"),
                            NurseID = new Guid("e6a3850b-7a1e-465c-83fd-57b1134c68d2")
                        },
                        new
                        {
                            ID = new Guid("038d24e4-d697-4ab6-a04a-70989e133c70"),
                            DoctorID = new Guid("dcd275c5-67c4-423b-a7b2-78ab917a2d5d"),
                            NurseID = new Guid("e5f97752-f18b-4b36-8c47-4d238cb0e01f")
                        });
                });

            modelBuilder.Entity("Hospital.Entities.Nurse", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<string>("PublicID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ShiftId");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Nurses");

                    b.HasData(
                        new
                        {
                            ID = new Guid("698d0579-913c-42af-8a45-924cd9f740bb"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775044959/a9da1dea6368ebb099100f489cc37cfe_zfh28g.jpg",
                            IsAccepted = true,
                            PublicID = "a9da1dea6368ebb099100f489cc37cfe_zfh28g",
                            ShiftId = new Guid("0288c0db-23d0-4cef-b74c-ef997285b18c"),
                            SpecializationId = new Guid("8a42cdba-ff58-4129-aea8-ae4c3b32f353"),
                            UserId = new Guid("354fa92a-6b54-4d12-b90c-9926dc906462")
                        },
                        new
                        {
                            ID = new Guid("e5f97752-f18b-4b36-8c47-4d238cb0e01f"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775045913/doctor10_ewtass.jpg",
                            IsAccepted = true,
                            PublicID = "doctor10_ewtass",
                            ShiftId = new Guid("3ba89da5-3a0d-44ff-97f9-f049bc9bdbe9"),
                            SpecializationId = new Guid("a5519f22-cefb-4771-a5e9-de7b40817df8"),
                            UserId = new Guid("02e72b22-0abd-4ce4-80d1-30b8c13f952b")
                        },
                        new
                        {
                            ID = new Guid("e6a3850b-7a1e-465c-83fd-57b1134c68d2"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775045922/doctor3_djf78l.jpg",
                            IsAccepted = true,
                            PublicID = "doctor3_djf78l",
                            ShiftId = new Guid("baaafe92-5c0f-420b-87f0-fb1da4868b41"),
                            SpecializationId = new Guid("1d3e1ea9-5265-4ff3-9875-d7ac37a2d8b2"),
                            UserId = new Guid("741d970d-f405-4bd1-94b2-eec2c3fb33e2")
                        },
                        new
                        {
                            ID = new Guid("9fb6048e-03ae-407f-a83e-51b6c5399b41"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775045919/doctor5_vwg329.jpg",
                            IsAccepted = true,
                            PublicID = "doctor5_vwg329",
                            ShiftId = new Guid("2cd29802-44c5-4559-8cc3-225984ae748f"),
                            SpecializationId = new Guid("d9daaa5d-2c41-4fa4-b709-709fcfcd5cc0"),
                            UserId = new Guid("355ad73e-6b7d-4ade-846d-7cab0da06629")
                        });
                });

            modelBuilder.Entity("Hospital.Entities.PatientAndDiagnose", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiagnoseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiagnoseId");

                    b.HasIndex("PatientId", "DiagnoseId")
                        .IsUnique();

                    b.ToTable("PatientsAndDiagnoses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DiagnoseId = new Guid("2edd634a-5c31-4f68-b9b5-58c2f5b80216"),
                            PatientId = new Guid("9783d8b3-014f-477a-b951-6ff87057b44f")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            DiagnoseId = new Guid("732a09fb-ad41-4059-829b-8f32cbf0ce2f"),
                            PatientId = new Guid("06999216-e4e9-4455-856d-5246259b2684")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            DiagnoseId = new Guid("02ce1c83-0198-4d90-9dc1-d697c61f936e"),
                            PatientId = new Guid("eac603b7-4022-4fb1-8c04-28db2f0f2162")
                        });
                });

            modelBuilder.Entity("Hospital.Entities.Room", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("bit");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            ID = new Guid("5b8e402c-ec9e-4e74-9cf2-ed1c05948e2a"),
                            IsTaken = false,
                            RoomNumber = 101
                        },
                        new
                        {
                            ID = new Guid("bb9bb784-dd42-4541-9ed2-01e7929a61ab"),
                            IsTaken = true,
                            RoomNumber = 102
                        },
                        new
                        {
                            ID = new Guid("1ba934d0-494e-431a-a7d6-2fff62af342a"),
                            IsTaken = false,
                            RoomNumber = 103
                        },
                        new
                        {
                            ID = new Guid("e748053a-f20a-4f80-a314-fbd9c2ac4e8a"),
                            IsTaken = true,
                            RoomNumber = 104
                        },
                        new
                        {
                            ID = new Guid("3970dc21-5df6-42ac-95db-261e18812d4c"),
                            IsTaken = true,
                            RoomNumber = 105
                        },
                        new
                        {
                            ID = new Guid("0de4b3b8-318e-42aa-b896-04cd14749d17"),
                            IsTaken = false,
                            RoomNumber = 106
                        },
                        new
                        {
                            ID = new Guid("92aa881b-d346-49d4-8b3d-a76e13469e99"),
                            IsTaken = true,
                            RoomNumber = 107
                        },
                        new
                        {
                            ID = new Guid("c4ad2bf7-9eea-4555-b637-00bc1d11cba3"),
                            IsTaken = true,
                            RoomNumber = 108
                        },
                        new
                        {
                            ID = new Guid("097fe7eb-86e3-43ea-a6da-c8a90373f27a"),
                            IsTaken = false,
                            RoomNumber = 109
                        },
                        new
                        {
                            ID = new Guid("9e9a26f4-3d2e-4f9a-bcf1-9e63e057a7c6"),
                            IsTaken = true,
                            RoomNumber = 201
                        },
                        new
                        {
                            ID = new Guid("c219c792-8a69-4850-ac40-a36f5f752786"),
                            IsTaken = true,
                            RoomNumber = 202
                        },
                        new
                        {
                            ID = new Guid("b5825cde-c8df-4d53-8f69-6d4e6d2683cb"),
                            IsTaken = false,
                            RoomNumber = 203
                        },
                        new
                        {
                            ID = new Guid("bee36b54-ff99-474a-b9de-82010ff3607c"),
                            IsTaken = true,
                            RoomNumber = 204
                        },
                        new
                        {
                            ID = new Guid("ba0b5ec2-b3c0-4901-8128-a3703d72ffd3"),
                            IsTaken = true,
                            RoomNumber = 205
                        },
                        new
                        {
                            ID = new Guid("f2a57cc6-8969-4f63-9691-2c449409ff4d"),
                            IsTaken = true,
                            RoomNumber = 206
                        },
                        new
                        {
                            ID = new Guid("85242158-d3c2-4542-bc27-88caf4a131c6"),
                            IsTaken = false,
                            RoomNumber = 207
                        },
                        new
                        {
                            ID = new Guid("44a7a821-54c8-4d2c-acf3-efbfbd75c18e"),
                            IsTaken = true,
                            RoomNumber = 208
                        },
                        new
                        {
                            ID = new Guid("88b657b6-c9c3-41eb-a26f-5d637c704533"),
                            IsTaken = false,
                            RoomNumber = 209
                        },
                        new
                        {
                            ID = new Guid("53546e3d-53ee-4e2c-861a-3cf5a3584893"),
                            IsTaken = true,
                            RoomNumber = 301
                        });
                });

            modelBuilder.Entity("Hospital.Entities.Specialization", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecializationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            ID = new Guid("8a42cdba-ff58-4129-aea8-ae4c3b32f353"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775117702/Screenshot_2026-04-02_111137_nbbhc6.png",
                            PublicID = "Screenshot_2026-04-02_111137_nbbhc6",
                            SpecializationName = "Infectious Disease"
                        },
                        new
                        {
                            ID = new Guid("7a67c94b-50fb-4043-83f1-afdade20b451"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775117702/Screenshot_2026-04-02_111310_zgxd8c.png",
                            PublicID = "Screenshot_2026-04-02_111310_zgxd8c",
                            SpecializationName = "Cardiology"
                        },
                        new
                        {
                            ID = new Guid("c484edec-d525-438a-92c4-ad80a9a41878"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775117702/Screenshot_2026-04-02_111403_uhhj71.png",
                            PublicID = "Screenshot_2026-04-02_111403_uhhj71",
                            SpecializationName = "Endocrinology"
                        },
                        new
                        {
                            ID = new Guid("9cfb1a19-193f-4bf7-bc4b-c744a89f59eb"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775117702/Screenshot_2026-04-02_111428_ukzxth.png",
                            PublicID = "Screenshot_2026-04-02_111428_ukzxth",
                            SpecializationName = "Pulmonology"
                        },
                        new
                        {
                            ID = new Guid("1d3e1ea9-5265-4ff3-9875-d7ac37a2d8b2"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775117702/Screenshot_2026-04-02_111521_asrj53.png",
                            PublicID = "Screenshot_2026-04-02_111521_asrj53",
                            SpecializationName = "Neurology"
                        },
                        new
                        {
                            ID = new Guid("e43cf086-24ad-4a75-b47e-549b8d8e467c"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775117702/Screenshot_2026-04-02_111550_rletvt.png",
                            PublicID = "Screenshot_2026-04-02_111550_rletvt",
                            SpecializationName = "Traumatology"
                        },
                        new
                        {
                            ID = new Guid("e82cc806-165f-4554-91f8-c9d9ae4909e5"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775117702/Screenshot_2026-04-02_111610_awmauh.png",
                            PublicID = "Screenshot_2026-04-02_111610_awmauh",
                            SpecializationName = "Allergy & Immunology"
                        },
                        new
                        {
                            ID = new Guid("a5519f22-cefb-4771-a5e9-de7b40817df8"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775117703/Screenshot_2026-04-02_111632_kl3iuj.png",
                            PublicID = "Screenshot_2026-04-02_111632_kl3iuj",
                            SpecializationName = "Rheumatology"
                        },
                        new
                        {
                            ID = new Guid("4ee4ce69-da26-4f66-85cf-30623200cbf4"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775117703/Screenshot_2026-04-02_111739_yxp8r4.png",
                            PublicID = "Screenshot_2026-04-02_111739_yxp8r4",
                            SpecializationName = "Orthopedics"
                        },
                        new
                        {
                            ID = new Guid("d9daaa5d-2c41-4fa4-b709-709fcfcd5cc0"),
                            ImageURL = "https://res.cloudinary.com/dyoxqki3d/image/upload/q_auto/f_auto/v1775117704/Screenshot_2026-04-02_111758_t9nbmc.png",
                            PublicID = "Screenshot_2026-04-02_111758_t9nbmc",
                            SpecializationName = "Respiratory"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Hospital.Data.Entities.Checkup", b =>
                {
                    b.HasOne("Hospital.Entities.Doctor", "Doctor")
                        .WithMany("Checkups")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hospital.Data.Entities.Patient", "Patient")
                        .WithMany("Checkups")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital.Data.Entities.Medication", b =>
                {
                    b.HasOne("Hospital.Entities.Diagnose", "Diagnose")
                        .WithMany("ListOfMedication")
                        .HasForeignKey("DiagnoseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnose");
                });

            modelBuilder.Entity("Hospital.Data.Entities.Patient", b =>
                {
                    b.HasOne("Hospital.Entities.Doctor", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Hospital.Entities.Room", "Room")
                        .WithMany("ListOfPatients")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Hospital.Data.Entities.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("Hospital.Data.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Doctor");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hospital.Entities.Doctor", b =>
                {
                    b.HasOne("Hospital.Data.Entities.Shift", "Shift")
                        .WithMany("ListOfDoctors")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Entities.Specialization", "Specialization")
                        .WithMany("ListOfDoctors")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Data.Entities.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("Hospital.Entities.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("Specialization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hospital.Entities.DoctorAndNurse", b =>
                {
                    b.HasOne("Hospital.Entities.Doctor", "Doctor")
                        .WithMany("DoctorNurses")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hospital.Entities.Nurse", "Nurse")
                        .WithMany("DoctorNurses")
                        .HasForeignKey("NurseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Nurse");
                });

            modelBuilder.Entity("Hospital.Entities.Nurse", b =>
                {
                    b.HasOne("Hospital.Data.Entities.Shift", "Shift")
                        .WithMany("ListOfNurses")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Entities.Specialization", "Specialization")
                        .WithMany("ListOfNurses")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Data.Entities.User", "User")
                        .WithOne("Nurse")
                        .HasForeignKey("Hospital.Entities.Nurse", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("Specialization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hospital.Entities.PatientAndDiagnose", b =>
                {
                    b.HasOne("Hospital.Entities.Diagnose", "Diagnose")
                        .WithMany("ListOfPatientsAndDiagnoses")
                        .HasForeignKey("DiagnoseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Data.Entities.Patient", "Patient")
                        .WithMany("PatientDiagnoses")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnose");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Hospital.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Hospital.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Hospital.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital.Data.Entities.Patient", b =>
                {
                    b.Navigation("Checkups");

                    b.Navigation("PatientDiagnoses");
                });

            modelBuilder.Entity("Hospital.Data.Entities.Shift", b =>
                {
                    b.Navigation("ListOfDoctors");

                    b.Navigation("ListOfNurses");
                });

            modelBuilder.Entity("Hospital.Data.Entities.User", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital.Entities.Diagnose", b =>
                {
                    b.Navigation("ListOfMedication");

                    b.Navigation("ListOfPatientsAndDiagnoses");
                });

            modelBuilder.Entity("Hospital.Entities.Doctor", b =>
                {
                    b.Navigation("Checkups");

                    b.Navigation("DoctorNurses");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("Hospital.Entities.Nurse", b =>
                {
                    b.Navigation("DoctorNurses");
                });

            modelBuilder.Entity("Hospital.Entities.Room", b =>
                {
                    b.Navigation("ListOfPatients");
                });

            modelBuilder.Entity("Hospital.Entities.Specialization", b =>
                {
                    b.Navigation("ListOfDoctors");

                    b.Navigation("ListOfNurses");
                });
#pragma warning restore 612, 618
        }
    }
}
