using Hospital.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Hospital.Data.Configurations
{
    public class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> builder)
        {
            builder.HasData(
                new User { Id = new Guid("e7d8baba-f7b1-4ed0-9bbb-139dc13e878e"), UserName = "kristen_gencheva", NormalizedUserName = "KRISTEN_GENCHEVA", Email = "kristeng@gmail.com", NormalizedEmail = "KRISTENG@GMAIL.COM", FirstName = "KRISTEN", LastName = "GENCHEVA", PasswordHash = "HASH", SecurityStamp = "S1", ConcurrencyStamp = "C1" },
                new User { Id = new Guid("072eae42-46ab-4919-aae5-073aef56c00d"), UserName = "ivan_petrov", NormalizedUserName = "IVAN_PETROV", Email = "ivanp@gmail.com", NormalizedEmail = "IVANP@GMAIL.COM", FirstName = "Ivan", LastName = "Petrov", PasswordHash = "HASH", SecurityStamp = "S2", ConcurrencyStamp = "C2" },
                new User { Id = new Guid("7c425879-d37a-48a6-91d9-2345120a3f6a"), UserName = "georgi_dimitrov", NormalizedUserName = "GEORGI_DIMITROV", Email = "gergid@gmail.com", NormalizedEmail = "GEORGID@GMAIL.COM", FirstName = "Georgi", LastName = "Dimitrov", PasswordHash = "HASH", SecurityStamp = "S3", ConcurrencyStamp = "C3" },
                new User { Id = new Guid("3d86822f-0eba-44ce-8484-27addbfe7357"), UserName = "nikolai_ivanov", NormalizedUserName = "NIKOLAI_IVANOV", Email = "nikolaii@gmail.com", NormalizedEmail = "NIKOLAII@GMAIL.COM", FirstName = "Nikolai", LastName = "Ivanov", PasswordHash = "HASH", SecurityStamp = "S4", ConcurrencyStamp = "C4" },
                new User { Id = new Guid("7dca2bf8-df73-4dbf-a602-52e147eafe1e"), UserName = "dimitur_stoyanov", NormalizedUserName = "DIMITUR_STOYANOV", Email = "dimiturs@gmail.com", NormalizedEmail = "DIMITURS@GMAIL.COM", FirstName = "Dimitur", LastName = "Stoyanov", PasswordHash = "HASH", SecurityStamp = "S5", ConcurrencyStamp = "C5" },
                new User { Id = new Guid("23b350b4-0dd6-43fc-b5dc-818faf2b74e6"), UserName = "aleksandur_nikolov", NormalizedUserName = "ALEKSANDUR_NIKOLOV", Email = "aleksandurn@gmail.com", NormalizedEmail = "ALEKSANDURN@GMAIL.COM", FirstName = "Aleksandur", LastName = "Nikolov", PasswordHash = "HASH", SecurityStamp = "S6", ConcurrencyStamp = "C6" },
                new User { Id = new Guid("d9ccb374-6b17-4e66-9c11-79412a9e1e93"), UserName = "yoana_ilieva", NormalizedUserName = "YOANA_ILIEVA", Email = "yoanai@gmail.com", NormalizedEmail = "YOANAI@GMAIL.COM", FirstName = "Yoana", LastName = "Ilieva", PasswordHash = "HASH", SecurityStamp = "S7", ConcurrencyStamp = "C7" },
                new User { Id = new Guid("30f2b4ed-e0e3-4443-8595-4dc6e26b3338"), UserName = "viktoriya_nikolova", NormalizedUserName = "VIKTORIYA_NIKOLOVA", Email = "viktoriyan@gmail.com", NormalizedEmail = "VIKTORIYAN@GMAIL.COM", FirstName = "Viktoriya", LastName = "Nikolova", PasswordHash = "HASH", SecurityStamp = "S8", ConcurrencyStamp = "C8" },
                new User { Id = new Guid("51daaed0-67e7-4c4a-b254-2745af5365df"), UserName = "anna_aleksandrova", NormalizedUserName = "ANNA_ALEKSANDROVA", Email = "annaa@gmail.com", NormalizedEmail = "ANNAA@GMAIL.COM", FirstName = "Anna", LastName = "Aleksandrova", PasswordHash = "HASH", SecurityStamp = "S9", ConcurrencyStamp = "C9" },
                new User { Id = new Guid("cbdfa704-0f6d-431f-8ede-dd952adacfc9"), UserName = "elena_petrova", NormalizedUserName = "ELENA_PETROVA", Email = "elenap@gmail.com", NormalizedEmail = "ELENAP@GMAIL.COM", FirstName = "Elena", LastName = "Petrova", PasswordHash = "HASH", SecurityStamp = "S10", ConcurrencyStamp = "C10" },
                new User { Id = new Guid("f6662c6a-414b-4b5c-ae1b-7b31103dd464"), UserName = "aleksandra_georgieva", NormalizedUserName = "ALEKSANDRA_GEORGIEVA", Email = "aleksandrag@gmail.com", NormalizedEmail = "ALEKSANDRAG@GMAIL.COM", FirstName = "Aleksandra", LastName = "Georgieva", PasswordHash = "HASH", SecurityStamp = "S11", ConcurrencyStamp = "C11" },

                new User { Id = new Guid("354fa92a-6b54-4d12-b90c-9926dc906462"), UserName = "maria_ivanova", NormalizedUserName = "MARIA_IVANOVA", Email = "mariai@gmail.com", NormalizedEmail = "MARIAI@GMAIL.COM", FirstName = "Maria", LastName = "Ivanova", PasswordHash = "HASH", SecurityStamp = "S12", ConcurrencyStamp = "C12" },
                new User { Id = new Guid("02e72b22-0abd-4ce4-80d1-30b8c13f952b"), UserName = "desislava_dimitrova", NormalizedUserName = "DESISLAVA_DIMITROVA", Email = "desid@gmail.com", NormalizedEmail = "DESID@GMAIL.COM", FirstName = "Desislava", LastName = "Dimitrova", PasswordHash = "HASH", SecurityStamp = "S13", ConcurrencyStamp = "C13" },
                new User { Id = new Guid("741d970d-f405-4bd1-94b2-eec2c3fb33e2"), UserName = "gergana_vasileva", NormalizedUserName = "GERGANA_VASILEVA", Email = "gerganav@gmail.com", NormalizedEmail = "GERGANAV@GMAIL.COM", FirstName = "Gergana", LastName = "Vasileva", PasswordHash = "HASH", SecurityStamp = "S14", ConcurrencyStamp = "C14" },
                new User { Id = new Guid("355ad73e-6b7d-4ade-846d-7cab0da06629"), UserName = "ralitsa_kostova", NormalizedUserName = "RALITSA_KOSTOVA", Email = "ralitsak@gmail.com", NormalizedEmail = "RALITSAK@GMAIL.COM", FirstName = "Ralitsa", LastName = "Kostova", PasswordHash = "HASH", SecurityStamp = "S15", ConcurrencyStamp = "C15" },
                new User { Id = new Guid("a7e0d718-a822-48db-b8ff-82cff6dbd5c7"), UserName = "petar_georgiev", NormalizedUserName = "PETAR_GEORGIEV", Email = "petarg@gmail.com", NormalizedEmail = "PETARG@GMAIL.COM", FirstName = "Petar", LastName = "Georgiev", PasswordHash = "HASH", SecurityStamp = "S16", ConcurrencyStamp = "C16" },
                new User { Id = new Guid("04347895-6b6e-4608-be4c-5f428b759669"), UserName = "stefan_kolev", NormalizedUserName = "STEFAN_KOLEV", Email = "stefank@gmail.com", NormalizedEmail = "STEFANK@GMAIL.COM", FirstName = "Stefan", LastName = "Kolev", PasswordHash = "HASH", SecurityStamp = "S17", ConcurrencyStamp = "C17" },
                new User { Id = new Guid("96747275-9c90-449e-a91c-eb6863183a27"), UserName = "borislav_todorov", NormalizedUserName = "BORISLAV_TODOROV", Email = "borislavt@gmail.com", NormalizedEmail = "BORISLAVT@GMAIL.COM", FirstName = "Borislav", LastName = "Todorov", PasswordHash = "HASH", SecurityStamp = "S18", ConcurrencyStamp = "C18" },
                new User { Id = new Guid("865c2545-7806-4857-a621-f035e520a596"), UserName = "hristo_vasilev", NormalizedUserName = "HRISTO_VASILEV", Email = "hristov@gmail.com", NormalizedEmail = "HRISTOV@GMAIL.COM", FirstName = "Hristo", LastName = "Vasilev", PasswordHash = "HASH", SecurityStamp = "S19", ConcurrencyStamp = "C19" },
                new User { Id = new Guid("c5982307-ef67-4b65-b438-8f9e1e3a240b"), UserName = "martin_iliev", NormalizedUserName = "MARTIN_ILIEV", Email = "martini@gmail.com", NormalizedEmail = "MARTINI@GMAIL.COM", FirstName = "Martin", LastName = "Iliev", PasswordHash = "HASH", SecurityStamp = "S20", ConcurrencyStamp = "C20" }
                );
        }
    }
}